### ISSUE TITLE
wish: dry-run feature

### ISSUE THREAD

**Issue by markstos** [xombiemp/ec2-purge-snapshots-lambda#2]
When starting out, it would build confidence and safety to have a "Dry Run" feature that allows you to see what would be deleted without actually deleting anything. 

For inspiration, here's a related project that provides an example of implementing a dry-run feature:
https://github.com/szkkentaro/rotate-snapshot

**Comment by xombiemp** [comment]
This already exists.  Check out the Test Function section of the Readme.  You need to pass the parameter "noop": "True".
