### ISSUE TITLE
wish: support volumes-and-tags 

### ISSUE THREAD

**Issue by markstos** [xombiemp/ec2-purge-snapshots-lambda#3]
Right now you can specify a collection of snapshots by providing an explicit list of volume IDs or some tags.

One of my goals for volumes to automatically get pruned for new hosts as needed. So I don't want to have to specify a new volume ID each time one comes online. I use a parallel tool that automatically generates the snapshots and tags them consistently. 

I want to keep, say, 30 snapshots per volume, but I want to specify the volumes by tag, not by volume ID. Specifying just a tag won't work, as I'll end up with 30 snapshots _overall_ that relate to the tag, instead of _30 snapshots per volume_ that relate to the tag. 

So, the desired logic boils down to "Retain X snapshots all volumes tagged with Y".

**Comment by AjeetK** [comment]
@markstos Did you find any solution regarding keeping specific number of snapshot corresponding to particular volume?

**Comment by AjeetK** [comment]
@markstos I have added the feature to "Retain X snapshots for the corresponding volume. [Here](https://github.com/AjeetK/ec2-purge-snapshots-lambda) is my forked repo.
The overall way it works is:

- Get all snapshots tagged with say "CreatedBy":"lambda" 
- Say, 100 snapshots are there with this tag.
- 50 belongs to volume-1 and 50 belongs to volume-2
- If we have specified to keep last 24 hours snapshots which were taken on hourly basis, then
- It will keep 24 snapshots for volume-1 and 24 snapshots for volume-2 and will purge the rest.

This is applicable only if you are purging on "TAGS" basis and not via "VOLUME_ID".
Hope this helps

**Comment by markstos** [comment]
@AjeetK My final solution was to write my own solution, which is [lambda-expire-snapshots](https://github.com/RideAmigosCorp/lambda-expire-snapshots), also installable via npm. 

To support it, I also write [grandfatherson](https://github.com/RideAmigosCorp/grandfatherson) which implements more advanced backup expiration logic, which allows you to specify per-volume how many backups will be kept for each hour, each day, each month and each year.

So I'm closing this "wish" request here now as I'm no longer waiting on this project to implement anything for me.

**Comment by xombiemp** [comment]
This functionality was added in https://github.com/xombiemp/ec2-purge-snapshots-lambda/commit/c1897749fde459ce499a0fbdfb19f8dcef46718e
