### ISSUE TITLE
VOLUMES=["all"] not working

### ISSUE THREAD

**Issue by mdmallardi** [xombiemp/ec2-purge-snapshots-lambda#4]
The documentation suggests that this should work, but as written I don't think this functionality works, and when I run this in my environment, I get the following message:

'No snapshots found with volume id: all'

**Comment by raakey** [comment]
Syntax error in module 'lambda_function': expected an indented block (lambda_function.py, line 13)


Getting above error,

**Comment by xombiemp** [comment]
The "all" functionality has been removed in https://github.com/xombiemp/ec2-purge-snapshots-lambda/commit/c1897749fde459ce499a0fbdfb19f8dcef46718e

Just use tags instead.
