### ISSUE TITLE
Getting Timezone error

### ISSUE THREAD

**Issue by Rupesh333** [xombiemp/ec2-purge-snapshots-lambda#6]
When I try to run this script to delete snapshot. Giving error : 

'time': KeyError
Traceback (most recent call last):
File "/var/task/ec2-purge-snapshots.py", line 174, in main
NOW = parser.parse(event['time']).astimezone(tz.gettz(TIMEZONE))
KeyError: 'time'

**Comment by sndpl** [comment]
If you schedule this lambda function with a cloudWatch Event, the event param of the main function will contain:
`{
  "account": "123456789012",
  "region": "us-east-1",
  "detail": {},
  "detail-type": "Scheduled Event",
  "source": "aws.events",
  "time": "1970-01-01T00:00:00Z",
  "id": "cdc73f9d-aea9-11e3-9d5a-835b769c0d9c",
  "resources": [
    "arn:aws:events:us-east-1:123456789012:rule/my-schedule"
  ]
}` 

This means if you want to run this script with a test you need to provide at least:
`{
  "noop": "True",
  "account": "123456789012",
  "time": "2017-12-08T10:54:00Z"
}`

**Comment by xombiemp** [comment]
View the readme for instructions on testing in the Lambda console.
